services:
  database:
    image: postgres:17
    container_name: romdoul_backend
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: romdoul_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "2707:5432"
    mem_limit: 512m
volumes:
  postgres_data: